[versions]
#jetbrains
kotlin = "1.9.21"
kotlinxSerializationJson = "1.6.2"
#Fossify
commons = "1.0.99"
#Gradle
gradlePlugins-agp = "8.2.1"
#Other
indicatorFastScroll = "4524cd0b61"
autofitTextView = "0.2.1"
#build
app-build-compileSDKVersion = "34"
app-build-targetSDK = "34"
app-build-minimumSDK = "23"
app-build-javaVersion = "VERSION_17"
app-build-kotlinJVMTarget = "17"
#versioning
app-version-appId = "org.fossify.dialer"
app-version-versionCode = "1"
app-version-versionName = "1.0.0"
[libraries]
#Fossify
fossify-commons = { module = "org.fossify.commons:release", version.ref = "commons" }
#Kotlin
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
#Other
indicator-fast-scroll = { module = "com.github.tibbi:IndicatorFastScroll", version.ref = "indicatorFastScroll" }
autofit-text-view = { module = "me.grantland:autofittextview", version.ref = "autofitTextView" }
[plugins]
android = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
